### ISSUE TITLE
托管问题

### ISSUE THREAD

**Issue by blankmiss** [bessyjl/resume#1]
我的博客基于hexo搭建在github上 我该怎么样将这个托管在我的博客上呢

**Comment by bessyjl** [comment]
> 我的博客基于hexo建造在github上我该怎么将这个托管在我的博客上呢

托管public文件夹下的文件就行了，可以创建一个子目录放进去，毕竟是生成的“静态文件”。我是上传到GitHub，然后部署在Netlify的。

**Comment by blankmiss** [comment]
因为hexo是上传 pubic到github库里的，所以我只需要在pubic的目录里新建一个子目录就可以成功托管到github上了么？
 
谢谢老哥的回答了

**Comment by bessyjl** [comment]
> 因为hexo是上传pubic到github库里的，所以我只需要在pubic的目录里新建一个子目录就可以成功托管到github上了么？
> 
> 谢谢老哥的回答了

你如果只上传/public文件夹下的资源文件的话，是需要修改部分代码的。否则可能导致部分资源加载不了，详见console的报错。如果不会的话，上传整个项目的代码，然后访问路径可能为："网站地址/resume/public"。如果要单独部署这个项目的话，就是"网站地址/public"。

**Comment by blankmiss** [comment]
我尝试了将公共文件下的资源文件长传，如老哥所料除了有标签其他什么都没有。看来我只能单独部署这个项目了，但是我如果将这个单独上传到github那怎么样在我的blog里访问呢，链接直接跳转走吗

**Comment by bessyjl** [comment]
> 我尝试了将公共文件下的资源文件长传，如老哥所料除有标签其他什么都没有。看来我只能单独部署这个项目了，但是我如果将这个单独上传到github那怎么样在我的blog里访问呢，链接直接替换走吗

如果是部署在子目录下，路径就用子目录。如果是单独部署，就用部署的自定义域就好了嘛。在blog里面访问的话，你可以像我一样，设置成全局友链。（可能用词或描述不恰当！）

**Comment by blankmiss** [comment]
不知道为什么 在目录里用npm install 就一堆报错然后npm run dev 也成功不了 
倒是原开发者的库我能成功运行

**Comment by blankmiss** [comment]
![](https://i.loli.net/2019/11/23/hHp1wRNYCyDrglk.png)

**Comment by bessyjl** [comment]
> 不知道为什么在目录里用npm install就一堆报错然后npm run dev也成功不了
> 倒是原开发者的库我能成功运行

很抱歉帮不了你，我的水平也有限。还是建议用原作者的，毕竟我这个repo是用来托管页面用的。

**Comment by blankmiss** [comment]
还是谢谢老哥的回答，我本地没成功倒是在网页上成功了
